FROM mirror.gcr.io/library/python:3.13-trixie

# Install uv and the required development libraries for compiling pygit2
RUN apt-get update -y && \
    apt-get install -y --no-install-recommends libgit2-dev pkg-config && \
    rm -rf /var/lib/apt/lists/* && \
    pip install uv

WORKDIR /app

COPY pyproject.toml uv.lock /app/

RUN uv sync --group docker-image-builder --no-install-project

RUN git config --global --add safe.directory /app

ENV VIRTUAL_ENV=/app/.venv
ENV PATH="${VIRTUAL_ENV}/bin:$PATH"
