name: Deploy Fork to Balena

on:
  push:
    branches:
      - master

jobs:
  balena_cloud_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Install Balena CLI
        run: |
          npm install -g balena-cli

      - name: Deploy to BalenaCloud
        run: |
          # Log into Balena CLI
          balena login --token ${{ secrets.BALENA_TOKEN }}
          
          # Manually create the missing docker-compose file from Anthias's template
          cp docker-compose.balena.yml.tmpl docker-compose.yml
          
          # Push cleanly using the native CLI build engine
          balena deploy it71/anthias-pi3 --build
